### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by wh0507** [wh0507/furima-31629#9]
自身のフリマアプリのURL
https://furima-31629.herokuapp.com/

Basic認証のIDとパスワード
ID：admin
PW：2222

出品者用のメールアドレスとパスワード
Mail：test1@test1.com
PW：rkddngml01

購入者用のメールアドレスとパスワード
Mail：test2@test2.com
PW：rkddngml01

購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242（16桁）
期間：12／25
セキュリティコード：123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
